# Generated by Django 5.2.8 on 2025-11-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgenapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profesor',
            old_name='puede_calificar',
            new_name='puede_ingresar_calificaciones',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Profesor'), ('3', 'Estudiante')], default='3', max_length=1),
        ),
    ]
