# Generated by Django 5.2.8 on 2025-11-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sgenapp', '0004_historialacciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='capacidad',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='materia',
            name='creditos',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
